### ISSUE TITLE
Scanned pages are in disarray

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#114]
Unfortunately the scanned pages in **Notizen zu den Farbtafeln by Johannes Itten** are in total disarray, structured by page numbers: http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31
It seems the chapter structure from emanuscripta is not followed: https://www.e-manuscripta.ch/zuzcmi/content/structure/4156649

Same with **Dokumente zur Ausstellung "Afrikanische Kunst aus Schweizer Sammlungen"** http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31?uri=https://resource.jila.zb.uzh.ch/collection/jila-7a7f650216bf4b9d81448fa9be6a3569, compare the page order in https://www.e-manuscripta.ch/zuzcmi/content/structure/4142468

Same with **Dokumente zum Vortrag "Kunst und Kunsterziehung"** http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31?uri=https://resource.jila.zb.uzh.ch/collection/jila-279a4c22df7940c7948646f72e60beff, compare the page order in https://www.e-manuscripta.ch/zuzcmi/content/thumbview/4156633

Same with **Dokumente zu einem Vortrag "Erziehung des Architekten"** http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31?uri=https://resource.jila.zb.uzh.ch/collection/jila-6939825c76714db88e83dc15e2fd1760, page [17] and [18] should be at the end. https://www.e-manuscripta.ch/zuzcmi/content/thumbview/4143783

**Comment by JoelleFischer** [comment]
In **Notizen zu den Farbtafeln by Johannes Itten** (http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31) are two pages that are in the wrong places. Page [39] is on position 62 instead of position 39. And page 10v comes last and should be in position 108.

**Dokumente zur Ausstellung «Afrikanische Kunst aus Schweizer Sammlungen»** (http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31?uri=https://resource.jila.zb.uzh.ch/collection/jila-7a7f650216bf4b9d81448fa9be6a3569) is still in disarray. From position 16 onwards pages are in the wrong places.

**Dokumente zum Vortrag «Kunst und Kunsterziehung»** (http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31?uri=https://resource.jila.zb.uzh.ch/collection/jila-279a4c22df7940c7948646f72e60beff) is fine.

**Dokumente zu einem Vortrag «Erziehung des Architekten»** (http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31?uri=https://resource.jila.zb.uzh.ch/collection/jila-6939825c76714db88e83dc15e2fd1760) is fine.

**Comment by JoelleFischer** [comment]
In **[Johannes Itten]: Farbkurs Ulm und andere Kurse** (http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31?uri=https://resource.jila.zb.uzh.ch/collection/jila-46687b818d664c20b32a5dbc994cf6fc) the first page is on the last position on JILA.

In **[Johannes Itten]: Kassel I. und II. Farbkurs u. a.** (http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31?uri=https://resource.jila.zb.uzh.ch/collection/jila-db7306d55dc244eb836dcfbdd3a577e0) the pages [45] and [46] are positioned fourth respectively third to last instead of positions 45 and 46. And the last two pages [71] and [72] are in the wrong sequence.

**Comment by JoelleFischer** [comment]
**Johannes Itten: Tagebuch Italien-Reise** (http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31) begins with pages [21] and [22] on JILA.

In **Johannes Itten: Skizzen zur Impressiven Farbenlehre** (http://10.51.1.212/resource/actor:AF0BA76E-E7EA-367A-AF8A-B3537D730E31) page 1v should be in position 4 instead of last. Pages 50 and 51 are on positions 20 and 21. Pages [22] and [23] are on the third and second to last position.

**Comment by JoelleFischer** [comment]
**Weihnachtsmappe von Emmy Anbelang** (http://10.51.1.212/resource/?uri=https://resource.jila.zb.uzh.ch/actor/AF0BA76E-E7EA-367A-AF8A-B3537D730E31) are the pages also in disarray. Pages [1] and [2] are in the positions 7 and 8.

**Comment by JoelleFischer** [comment]
The pages are still in disarray on JILA additionally the following have been found:

**[Johannes Itten]: IV. Kurs Rheinhardswaldschule** (http://10.51.1.212/resource/actor:74639585-9140-373B-865A-843A1B5BD4AE)

**Exzerpte aus "Lehrbuch der Physiologie" von E. Aberhalden** (http://10.51.1.212/resource/actor:747FFCEB-CFB1-3869-B634-F6F7AB54CDE0)

**Brief von Walter Tralau, Wera Meyer-Waldeck und Gerhard Marcks** (http://10.51.1.212/resource/actor:8359D19D-9B99-3A99-AFCE-A32C541ACBCA)

**Johannes Itten: Beschreibung einer chinesischen Weihstele** (http://10.51.1.212/resource/actor:394868E8-6456-358F-BB8E-5DFF6302B4C6)

**Manuskripte zur Farbenlehre. Ordner III** (http://10.51.1.212/resource/actor:144F1BD6-678E-31F0-B85C-0D2316F90FF2)

**Johannes Itten an Anna Höllering** (http://10.51.1.212/resource/actor:C6EACB06-CBFD-3590-97CB-58B92FE0604F)

**Johannes Itten an Alfred Altherr** (http://10.51.1.212/resource/actor:74BD0845-FB10-3B7D-9915-895E3A4F9817)

**Entwurfsmanuskript 1 zum Vortrag "Hölzel und sein Kreis"** (http://10.51.1.212/resource/actor:F22B7C71-FF39-3C98-97D9-2E8D8FA28C76)

**Comment by JoelleFischer** [comment]
Further documents in disarray:

**Aufsatz "Der Vorkurs"** (http://10.51.1.212/resource/?uri=https://resource.jila.zb.uzh.ch/actor/AF0BA76E-E7EA-367A-AF8A-B3537D730E31)

**Johannes Itten: Farblehre Bd. II** (http://10.51.1.212/resource/?uri=https://resource.jila.zb.uzh.ch/actor/AF0BA76E-E7EA-367A-AF8A-B3537D730E31)

**Johannes Itten: Farblehre Bd. III** (http://10.51.1.212/resource/?uri=https://resource.jila.zb.uzh.ch/actor/AF0BA76E-E7EA-367A-AF8A-B3537D730E31)

**Notizen über Gandhi** (http://10.51.1.212/resource/?uri=https://resource.jila.zb.uzh.ch/actor/AF0BA76E-E7EA-367A-AF8A-B3537D730E31)

**Vortrag "Typenlehre"** (http://10.51.1.212/resource/?uri=https://resource.jila.zb.uzh.ch/actor/AF0BA76E-E7EA-367A-AF8A-B3537D730E31)

**Johannes Itten: Die Ausbildung der Industrial Designer** (http://10.51.1.212/resource/?uri=https://resource.jila.zb.uzh.ch/actor/AF0BA76E-E7EA-367A-AF8A-B3537D730E31)

**Comment by fkraeutli** [comment]
The issue is that we have no metadata about the 'proper' order of documents. Are they in the correct order in the IIIF manifests?

**Comment by fkraeutli** [comment]
Great, then we might derive the order from there

**Comment by fkraeutli** [comment]
I implemented the mapping to use the IIIF manifest order. will remap now

**Comment by fkraeutli** [comment]
Images are now ordererd as they are in the IIIF Manifests. For example: http://10.51.1.212/resource/?uri=https://resource.jila.zb.uzh.ch/collection/jila-8e8f7339c82f4cb4bfbe665e47785ada

Can you check @JoelleFischer ?

**Comment by JoelleFischer** [comment]
Unfortunately the examples I checked are still in the wrong order.

**Comment by fkraeutli** [comment]
Ah I found the problem. The positions are correct in the data, but they have been ordered alphabetically. So not 0, 1, 2 but 0, 1, 10, 100. I will change this in the mapping so it's fixed at the source

**Comment by JoelleFischer** [comment]
Thanks. You seem to have solved the problem. I've checked most of the above mentioned documents and they are all in the right order now.

**Comment by fkraeutli** [comment]
That's great to hear! Thanks for your patience
